"""Bake smooth displacement maps for the "line boil" filter (cheaper than per-frame feTurbulence).

Usage: python pipeline/make_disp.py video/src/engine/dispMaps.ts
Writes a TS module exporting N small PNG data URIs (R = x offset, G = y offset, 128 = no offset).
"""
import base64
import io
import sys

import numpy as np
from PIL import Image

N, W, H = 12, 240, 136
GRID = (9, 15)  # low-res random grid -> smooth blobs roughly every ~120px at 1920 wide


def smooth_noise(rng: np.random.Generator) -> np.ndarray:
    g = rng.uniform(-1, 1, GRID).astype(np.float32)
    im = Image.fromarray(g).resize((W, H), Image.BICUBIC)
    a = np.asarray(im)
    a = a / (np.abs(a).max() + 1e-6)
    return a


def main() -> None:
    out = sys.argv[1]
    rng = np.random.default_rng(7)
    uris = []
    for _ in range(N):
        r = smooth_noise(rng)
        g = smooth_noise(rng)
        rgb = np.stack([r, g, np.zeros_like(r)], axis=-1)
        rgb = np.clip(128 + rgb * 127, 0, 255).astype(np.uint8)
        buf = io.BytesIO()
        Image.fromarray(rgb, "RGB").save(buf, "PNG", optimize=True)
        uris.append("data:image/png;base64," + base64.b64encode(buf.getvalue()).decode())
    with open(out, "w") as f:
        f.write("// Generated by pipeline/make_disp.py — smooth displacement maps for the line-boil filter.\n")
        f.write("export const DISP_MAPS: string[] = [\n")
        for u in uris:
            f.write(f'  "{u}",\n')
        f.write("];\n")
    print("wrote", out, sum(len(u) for u in uris) // 1024, "KB")


if __name__ == "__main__":
    main()
